### ISSUE TITLE
Execute examples remotely

### ISSUE THREAD

**Issue by anfelbar** [EngFlow/example#65]
# About

The following examples directories `build/test` are successful when executing remotely on opal: `cpp`, `docker`, `genrules`, `go`, `java`,  `kotlin`, `perl`, `python` and `scala`. The remaining, however, need some work.

# Tasks

- [ ] csharp: `no matching toolchains found for types @io_bazel_rules_dotnet//dotnet:toolchain_type_csharp_core`
- [ ] swift: `Error forking process '/usr/share/swift/usr/bin/swiftc'. No such file or directory`
- [ ] typecript: `Error: Cannot find module 'google-protobuf'`

**Comment by anfelbar** [comment]
csharp works remotely:

Linux:
```
 bazel run //csharp/... --config=clang --config=canary --platforms @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100
```

Macos:
```
 bazel run //csharp/... --config=clang --config=canary --platforms @io_bazel_rules_dotnet//dotnet/toolchain:darwin_amd64_3.1.100
```
